# Generated by Django 3.1.4 on 2020-12-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=128)),
                ('passwd', models.CharField(max_length=128)),
                ('addr', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
